### ISSUE TITLE
Error when reading request headers on /health check

### ISSUE THREAD

**Issue by suntong** [mymmrac/echo-bot#1]
Hi,

I'm getting `error when reading request headers` for

https://github.com/mymmrac/echo-bot/blob/3cb025c019843e8d80a5a2c0a1db81b605d01459/main.go#L33-L36

```
Handling updates...
2023/04/24 12:32:55 error when serving connection "127.0.0.1:443"<->"127.0.0.1:45088": error when reading request headers: EOF. Buffer size=517, contents: "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x90w\x9c\x1c\xe5:\xd6\x10\xe1\xcf\xccl\x18\a\\\xbe\x80\xb9\xd9\x0fsH\xb1\xc6\x1d\xf1\x18\xfaÑ¾}\x84 P\xf6\x8c\xbb?8`\xdf6X\xe8Ù
```

My `/health` HTTP GET request is somehow blocked, until I have to kill it, at which time the above error is generated:

```
$ curl -v https://localhost/health || date
*   Trying ::1:443...
* connect to ::1 port 443 failed: Connection refused
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
Terminated
Mon Apr 24 12:32:55 EDT 2023
```

What goes wrong please?

Full test code is at:
https://github.com/suntong/go_telebot_demos/blob/master/telego/aws_echo/aws_echo-bot.go

Thanks

**Comment by mymmrac** [comment]
Hmm, are you using ngrok or something similar? Because, when I was testing I got same error.

I think there is something with ngrok and port 443, because once I changed port to any other (8080 for example) it started to work (I also started ngrok for port 8080).

> Or another issue is that when you are running something on HTTPS (port 443) it's not that simple to just curl, becouse you also need self sined certificates for localhost, but you don't have them.

**Comment by suntong** [comment]
THANKS!!
